# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v8.3.10
_src_path: gh:Tecnativa/doodba-copier-template
backup_dst: ""
cidr_whitelist: null
domains_prod: null
domains_test: null
gitlab_url: ""
odoo_dbfilter: ^prod
odoo_initial_lang: fr_CH
odoo_listdb: false
odoo_oci_image: docker.jguenat.ch/jguenat
odoo_proxy: ""
odoo_version: 18.0
paths_without_crawlers:
  - /web
  - /website/info
postgres_dbname: prod
postgres_exposed: false
postgres_username: odoo
postgres_version: "15"
project_author: Julien Guenat
project_license: AGPL-3.0-or-later
project_name: jguenat
smtp_default_from: ""
smtp_relay_host: ""
